run_test "echo (allow)"                          "echo hello"                         "allow"
run_test "ls (allow)"                            "ls"                                 "allow"
run_test "ls -la (allow)"                        "ls -la"                             "allow"
run_test "cat (allow)"                           "cat /etc/passwd"                    "allow"
run_test "grep (allow)"                          "grep -r foo src/"                   "allow"
run_test "jq (allow)"                            "jq '.name' package.json"            "allow"
run_test "diff (allow)"                          "diff a.txt b.txt"                   "allow"
run_test "find (allow)"                          "find . -name '*.sh'"                "allow"
run_test "git status (allow)"                    "git status"                         "allow"
run_test "git log --oneline (allow)"             "git log --oneline"                  "allow"
run_test "git add (allow)"                       "git add src/foo.sh"                 "allow"
run_test "git pull (allow)"                      "git pull origin main"               "allow"
run_test "git checkout (allow)"                  "git checkout feature-branch"        "allow"
run_test "git stash (allow)"                     "git stash"                          "allow"
run_test "git blame (allow)"                     "git blame src/foo.sh"               "allow"
run_test "gh pr list (allow)"                    "gh pr list"                         "allow"
run_test "gh pr diff (allow)"                    "gh pr diff 42"                      "allow"
run_test "gh issue view (allow)"                 "gh issue view 123"                  "allow"
run_test "gh run list (allow)"                   "gh run list"                        "allow"
run_test "gh auth status (allow)"                "gh auth status"                     "allow"
run_test "gh search (allow)"                     "gh search issues --label bug"       "allow"
run_test "git push (ask)"                "git push origin main"               "ask"
run_test "git commit (ask)"              "git commit -m msg"                  "ask"
run_test "git rebase (ask)"              "git rebase main"                    "ask"
run_test "git reset (ask)"               "git reset HEAD~1"                   "ask"
run_test "git branch -D (ask)"           "git branch -D old-branch"           "ask"
run_test "gh pr create (ask)"            "gh pr create --title foo"           "ask"
run_test "gh issue comment (ask)"        "gh issue comment 1 --body hi"       "ask"
run_test "gh issue close (ask)"          "gh issue close 1"                   "ask"
run_test "gh pr edit (ask)"              "gh pr edit 42 --title new"          "ask"
run_test "gh release create (ask)"       "gh release create v1.0"             "ask"
run_test "git push --force (deny beats ask)"     "git push origin --force"            "deny"
run_test "git push -f (deny)"                    "git push -f"                        "deny"
run_test "git reset --hard (deny)"               "git reset --hard HEAD"              "deny"
run_test "git clean -f (deny)"                   "git clean -f"                       "deny"
run_test "rm -rf (deny)"                         "rm -rf /some/path"                  "deny"
run_test "chmod 777 (deny)"                      "chmod 777 /etc/passwd"              "deny"
run_test "npm run (allow)"                       "npm run build"                      "allow"
run_test "node --version (allow)"               "node --version"                     "allow"
run_test "docker ps (allow)"                    "docker ps -a"                       "allow"
run_test "docker images (allow)"                "docker images"                      "allow"
run_test "python3 -m py_compile (allow)"        "python3 -m py_compile foo.py"       "allow"
run_test "python3 --version (allow)"            "python3 --version"                  "allow"
run_test "git ls-tree (allow)"                  "git ls-tree HEAD"                   "allow"
run_test "gh project list (allow)"              "gh project list"                    "allow"
run_test "gh project item-list (allow)"         "gh project item-list --owner org"   "allow"
run_test "unknown command (defer)"               "make build"                         "defer"
run_test_deny_reason "chmod 777: reason surfaced" "chmod 777 /tmp/file" "restrictive mode"
