run_test "echo (allow)"                          "echo hello"                         "allow"
run_test "ls (allow)"                            "ls"                                 "allow"
run_test "ls -la (allow)"                        "ls -la"                             "allow"
run_test "cat (allow)"                           "cat /etc/passwd"                    "allow"
run_test "grep (allow)"                          "grep -r foo src/"                   "allow"
run_test "jq (allow)"                            "jq '.name' package.json"            "allow"
run_test "diff (allow)"                          "diff a.txt b.txt"                   "allow"
run_test "find (allow)"                          "find . -name '*.sh'"                "allow"
run_test "git status (allow)"                    "git status"                         "allow"
run_test "git log --oneline (allow)"             "git log --oneline"                  "allow"
run_test "git add (allow)"                       "git add src/foo.sh"                 "allow"
run_test "git pull (allow)"                      "git pull origin main"               "allow"
run_test "git checkout (allow)"                  "git checkout feature-branch"        "allow"
run_test "git stash (allow)"                     "git stash"                          "allow"
run_test "git blame (allow)"                     "git blame src/foo.sh"               "allow"
run_test "gh pr list (allow)"                    "gh pr list"                         "allow"
run_test "gh pr diff (allow)"                    "gh pr diff 42"                      "allow"
run_test "gh issue view (allow)"                 "gh issue view 123"                  "allow"
run_test "gh run list (allow)"                   "gh run list"                        "allow"
run_test "gh auth status (allow)"                "gh auth status"                     "allow"
run_test "gh search (allow)"                     "gh search issues --label bug"       "allow"
run_test "git push (ask → defer)"                "git push origin main"               "defer"
run_test "git commit (ask → defer)"              "git commit -m msg"                  "defer"
run_test "git rebase (ask → defer)"              "git rebase main"                    "defer"
run_test "git reset (ask → defer)"               "git reset HEAD~1"                   "defer"
run_test "git branch -D (ask → defer)"           "git branch -D old-branch"           "defer"
run_test "gh pr create (ask → defer)"            "gh pr create --title foo"           "defer"
run_test "gh issue comment (ask → defer)"        "gh issue comment 1 --body hi"       "defer"
run_test "gh issue close (ask → defer)"          "gh issue close 1"                   "defer"
run_test "gh pr edit (ask → defer)"              "gh pr edit 42 --title new"          "defer"
run_test "gh release create (ask → defer)"       "gh release create v1.0"             "defer"
run_test "git push --force (deny beats ask)"     "git push origin --force"            "deny"
run_test "git push -f (deny)"                    "git push -f"                        "deny"
run_test "git reset --hard (deny)"               "git reset --hard HEAD"              "deny"
run_test "git clean -f (deny)"                   "git clean -f"                       "deny"
run_test "rm -rf (deny)"                         "rm -rf /some/path"                  "deny"
run_test "chmod 777 (deny)"                      "chmod 777 /etc/passwd"              "deny"
run_test "unknown command (defer)"               "make build"                         "defer"
