run_test "curl GET default (allow)"        "curl https://api.example.com/status"       "allow"
run_test "curl -s GET (allow)"             "curl -s https://api.example.com/v1/users"  "allow"
run_test "curl -X GET (allow)"             "curl -X GET https://api.example.com"       "allow"
run_test "curl -X HEAD (allow)"            "curl -X HEAD https://api.example.com"      "allow"
run_test "curl -X POST (defer)"            "curl -X POST https://api.example.com"      "defer"
run_test "curl -d data (defer)"            "curl -d '{\"key\":\"val\"}' https://..."   "defer"
run_test "curl -F form upload (defer)"     "curl -F file=@photo.jpg https://..."       "defer"
run_test "curl -X DELETE (defer)"          "curl -X DELETE https://api.example.com/1" "defer"
run_test "non-curl command (defer)"        "wget https://example.com"                  "defer"
